### ISSUE TITLE
Deploying to Netlify seems to break

### ISSUE THREAD

**Issue by mohammedmulazada** [zachleat/speedlify#30]
I basically hit the 'push to Netlify' button and get this error:

```bash
12:37:30 AM: Problem writing Eleventy templates: (more in DEBUG output)
12:37:30 AM: > Having trouble rendering 11ty.js template ./api.11ty.js
12:37:30 AM: `TemplateContentRenderError` was thrown
12:37:30 AM: > Cannot read property '5fbe07d5' of undefined
12:37:30 AM: `TypeError` was thrown:
12:37:30 AM:     TypeError: Cannot read property '5fbe07d5' of undefined
12:37:30 AM:         at ApiEntry.render (/opt/build/repo/api.11ty.js:19:31)
12:37:30 AM:         at JavaScript.<anonymous> (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/JavaScript.js:129:43)
12:37:30 AM:         at Template.render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:199:28)
12:37:30 AM:         at processTicksAndRejections (internal/process/task_queues.js:97:5)
12:37:30 AM:         at async Template._getContent (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:547:12)
12:37:30 AM:         at async Template.getTemplateMapContent (/opt/build/repo/node_modules/@11ty/eleventy/src/Template.js:732:19)
12:37:30 AM:         at async TemplateMap.populateContentDataInMap (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateMap.js:359:39)
12:37:30 AM:         at async TemplateMap.cache (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateMap.js:303:5)
12:37:30 AM:         at async TemplateWriter._createTemplateMap (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:170:5)
12:37:30 AM:         at async TemplateWriter.writeTemplates (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateWriter.js:203:5)
12:37:30 AM: Copied 2 files / Wrote 0 files in 0.13 seconds (v0.11.0)
12:37:30 AM: npm ERR! code ELIFECYCLE
12:37:30 AM: npm ERR! errno 1
12:37:30 AM: npm ERR! speedlify@1.0.0 build: `npx @11ty/eleventy --quiet`
12:37:30 AM: npm ERR! Exit status 1
12:37:30 AM: npm ERR!
```

Can anyone try deploying to Netlify and confirm if it works for them?

**Comment by zachleat** [comment]
Ah this happens when you have no test runs or categories. I added a sample category with one site—can you try again?

**Comment by mohammedmulazada** [comment]
Thank you @zachleat, that fixes the issue I was having :)

**Comment by zachleat** [comment]
Great!
