### ISSUE TITLE
Building Failed.

### ISSUE THREAD

**Issue by h2kyaw** [zachleat/speedlify#69]
Debug log_
```
11:23:45 AM: Netlify Build                                                 
11:23:45 AM: ────────────────────────────────────────────────────────────────
11:23:45 AM: ​
11:23:45 AM: ❯ Version
11:23:45 AM:   @netlify/build 29.21.1
11:23:45 AM: ​
11:23:45 AM: ❯ Flags
11:23:45 AM:   baseRelDir: true
11:23:45 AM:   buildId: 651263bfcbf1430edabef215
11:23:45 AM:   deployId: 651263bfcbf1430edabef217
11:23:45 AM: ​
11:23:45 AM: ❯ Current directory
11:23:45 AM:   /opt/build/repo
11:23:45 AM: ​
11:23:45 AM: ❯ Config file
11:23:45 AM:   /opt/build/repo/netlify.toml
11:23:45 AM: ​
11:23:45 AM: ❯ Context
11:23:45 AM:   production
11:23:45 AM: ​
11:23:45 AM: ❯ Installing plugins
11:23:45 AM:    - @netlify/plugin-lighthouse@5.0.0
11:23:52 AM: ​
11:23:52 AM: ❯ Loading plugins
11:23:52 AM:    - @netlify/plugin-lighthouse@5.0.0 from Netlify app
11:23:52 AM:    - ./plugins/keep-data-cache@1.0.0 from netlify.toml
11:23:54 AM: ​
11:23:54 AM: ./plugins/keep-data-cache (onPreBuild event)                  
11:23:54 AM: ────────────────────────────────────────────────────────────────
11:23:54 AM: ​
11:23:54 AM: ​
11:23:54 AM: (./plugins/keep-data-cache onPreBuild completed in 7ms)
11:23:54 AM: ​
11:23:54 AM: build.command from netlify.toml                               
11:23:54 AM: ────────────────────────────────────────────────────────────────
11:23:54 AM: ​
11:23:54 AM: $ npm run build-production
11:23:54 AM: > speedlify@1.0.0 build-production
11:23:54 AM: > npm run test-pages && npm run build && npm run zip-results
11:23:54 AM: > speedlify@1.0.0 test-pages
11:23:54 AM: > node run-tests
11:23:55 AM: There are no known last run timestamps
11:23:55 AM: Skipping ksvblog (you told me to in your site config)
11:23:55 AM: > speedlify@1.0.0 build
11:23:55 AM: > npx @11ty/eleventy --quiet
11:23:56 AM: [11ty] Copied 2 files / Wrote 5 files in 0.11 seconds (v2.0.1)
11:23:56 AM: > speedlify@1.0.0 zip-results
11:23:56 AM: > node zip-results.js
11:23:56 AM: node:child_process:929
11:23:56 AM:     throw err;
11:23:56 AM:     ^
11:23:56 AM: Error: Command failed: zip -r -y /opt/build/repo/_site/results.zip results
11:23:56 AM:     at checkExecSyncError (node:child_process:890:11)
11:23:56 AM:     at Object.execFileSync (node:child_process:926:15)
11:23:56 AM:     at Object.zipSync (/opt/build/repo/node_modules/cross-zip/index.js:81:6)
11:23:56 AM:     at Object.<anonymous> (/opt/build/repo/zip-results.js:7:5)
11:23:56 AM:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
11:23:56 AM:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
11:23:56 AM:     at Module.load (node:internal/modules/cjs/loader:1119:32)
11:23:56 AM:     at Module._load (node:internal/modules/cjs/loader:960:12)
11:23:56 AM:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
11:23:56 AM:   status: 12,
11:23:56 AM:   signal: null,
11:23:56 AM:   output: [
11:23:56 AM:     null,
11:23:56 AM:     Buffer(131) [Uint8Array] [
11:23:56 AM:         9, 122, 105, 112,  32, 119,  97, 114, 110, 105, 110, 103,
11:23:56 AM:        58,  32, 110,  97, 109, 101,  32, 110, 111, 116,  32, 109,
11:23:56 AM:        97, 116,  99, 104, 101, 100,  58,  32, 114, 101, 115, 117,
11:23:56 AM:       108, 116, 115,  10,  10, 122, 105, 112,  32, 101, 114, 114,
11:23:56 AM:       111, 114,  58,  32,  78, 111, 116, 104, 105, 110, 103,  32,
11:23:56 AM:       116, 111,  32, 100, 111,  33,  32,  40, 116, 114, 121,  58,
11:23:56 AM:        32, 122, 105, 112,  32,  45, 114,  32,  45, 121,  32,  47,
11:23:56 AM:       111, 112, 116,  47,  98, 117, 105, 108, 100,  47, 114, 101,
11:23:56 AM:       112, 111,  47,  95,
11:23:56 AM:       ... 31 more items
11:23:56 AM:     ],
11:23:56 AM:     Buffer(0) [Uint8Array] []
11:23:56 AM:   ],
11:23:56 AM:   pid: 4195,
11:23:56 AM:   stdout: Buffer(131) [Uint8Array] [
11:23:56 AM:       9, 122, 105, 112,  32, 119,  97, 114, 110, 105, 110, 103,
11:23:56 AM:      58,  32, 110,  97, 109, 101,  32, 110, 111, 116,  32, 109,
11:23:56 AM:      97, 116,  99, 104, 101, 100,  58,  32, 114, 101, 115, 117,
11:23:56 AM:     108, 116, 115,  10,  10, 122, 105, 112,  32, 101, 114, 114,
11:23:56 AM:     111, 114,  58,  32,  78, 111, 116, 104, 105, 110, 103,  32,
11:23:56 AM:     116, 111,  32, 100, 111,  33,  32,  40, 116, 114, 121,  58,
11:23:56 AM:      32, 122, 105, 112,  32,  45, 114,  32,  45, 121,  32,  47,
11:23:56 AM:     111, 112, 116,  47,  98, 117, 105, 108, 100,  47, 114, 101,
11:23:56 AM:     112, 111,  47,  95,
11:23:56 AM:     ... 31 more items
11:23:56 AM:   ],
11:23:56 AM:   stderr: Buffer(0) [Uint8Array] []
11:23:56 AM: }
11:23:56 AM: Node.js v18.18.0
11:23:56 AM: ​
11:23:56 AM: "build.command" failed                                        
11:23:56 AM: ────────────────────────────────────────────────────────────────
11:23:56 AM: ​
11:23:56 AM:   Error message
11:23:56 AM:   Command failed with exit code 1: npm run build-production (https://ntl.fyi/exit-code-1)
11:23:56 AM: ​
11:23:56 AM:   Error location
11:23:56 AM:   In build.command from netlify.toml:
11:23:56 AM:   npm run build-production
11:23:56 AM: ​
11:23:56 AM:   Resolved config
11:23:56 AM:   build:
11:23:56 AM:     command: npm run build-production
11:23:56 AM:     commandOrigin: config
11:23:56 AM:     environment:
11:23:56 AM:       - PUPPETEER_CACHE_DIR
11:23:56 AM:     publish: /opt/build/repo/_site
11:23:56 AM:     publishOrigin: config
11:23:56 AM:   headers:
11:23:57 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:23:57 AM: Failing build: Failed to build site
11:23:58 AM: Finished processing build request in 36.886s
11:23:57 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
```

**Comment by h2kyaw** [comment]
nvm, I made new **_data/results** folder as #66 Mentioned.

**Comment by h2kyaw** [comment]
nvm, I made new _data/results folder as #66 Mentioned.
